name: CI check on every PR and master push
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'Makefile'
      - 'config.json'
  push:
    branches:
      - 'master'

jobs:
  ci:
    name: CI check on every push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: run test cases
        run: make test && make

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
          verbose: true
